// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOZi2bfAY-tub_kAJU-IFbLcr06HBMRPc',
    appId: '1:586801802275:web:0cdea214d0d4ed234f1596',
    messagingSenderId: '586801802275',
    projectId: 'fier-aomely-app',
    authDomain: 'fier-aomely-app.firebaseapp.com',
    storageBucket: 'fier-aomely-app.appspot.com',
    measurementId: 'G-QSJD6E35SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBik-3AqkKcBcIGXkfzw0P9Nc8grzb2oFA',
    appId: '1:586801802275:android:f9389eec79ce764f4f1596',
    messagingSenderId: '586801802275',
    projectId: 'fier-aomely-app',
    storageBucket: 'fier-aomely-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3_0zTuouqsGPISnI4PoP8n7lia2tNkkI',
    appId: '1:586801802275:ios:279d8b875af11e604f1596',
    messagingSenderId: '586801802275',
    projectId: 'fier-aomely-app',
    storageBucket: 'fier-aomely-app.appspot.com',
    iosBundleId: 'com.example.apphomely',
  );
}
